### ISSUE TITLE
登录成功用的是PHP5.3n 报错了 求帮忙下

### ISSUE THREAD

**Issue by Liberxue** [nangge/webchat-robot#1]
Notice: Undefined index: synckey in D:\phpStudy\WWW\webchat-robot\index.php on line 54

Notice: Use of undefined constant CURLOPT_SAFE_UPLOAD - assumed 'CURLOPT_SAFE_UPLOAD' in D:\phpStudy\WWW\webchat-robot\src\wechat.php on line 90

Warning: curl_setopt() expects parameter 2 to be long, string given in D:\phpStudy\WWW\webchat-robot\src\wechat.php on line 90
{ "BaseResponse": { "Ret": 1100, "ErrMsg": "" } , "AddMsgCount": 0, "AddMsgList": [], "ModContactCount": 0, "ModContactList": [], "DelContactCount": 0, "DelContactList": [], "ModChatRoomMemberCount": 0, "ModChatRoomMemberList": [], "Profile": { "BitFlag": 0, "UserName": { "Buff": "" } , "NickName": { "Buff": "" } , "BindUin": 0, "BindEmail": { "Buff": "" } , "BindMobile": { "Buff": "" } , "Status": 0, "Sex": 0, "PersonalCard": 0, "Alias": "", "HeadImgUpdateFlag": 0, "HeadImgUrl": "", "Signature": "" } , "ContinueFlag": 0, "SyncKey": { "Count": 0, "List": [] } , "SKey": "", "SyncCheckKey": { "Count": 0, "List": [] } }

**Comment by nangge** [comment]
通过你的错误提示可以看到，CURl的这一选项 CURLOPT_SAFE_UPLOAD报错，该选项在PHP 5.5.0 中添加；
你可以尝试把php的版本升高至5.5，phpstudy可以很方便的改变；或者找到
`\webchat-robot\src\wechat.php on line 90` 删除该选项；

**Comment by Liberxue** [comment]
好的我试下您官网的也是获取不到 ，提示
![image](https://cloud.githubusercontent.com/assets/5831248/20169130/c2c0942a-a760-11e6-9e84-632a374e8b21.png)
![image](https://cloud.githubusercontent.com/assets/5831248/20169147/d2de91fe-a760-11e6-80fa-334c9e019a11.png)

**Comment by nangge** [comment]
通过你的错误提示可以看到，CURl的这一选项 CURLOPT_SAFE_UPLOAD报错，该选项在PHP 5.5.0 中添加；
你可以尝试把php的版本升高至5.5，phpstudy可以很方便的改变；或者找到
\webchat-robot\src\wechat.php on line 90 删除该选项；

**Comment by Liberxue** [comment]
现在好了 ，但是 跟您官网的一样错误是   “与微信服务器通讯出错，请刷新重试或重新扫码登陆！ ”http://webchat.5none.com/index.php?act=chat
![image](https://cloud.githubusercontent.com/assets/5831248/20169383/371009a4-a762-11e6-82c2-c65a70b8e205.png)

**Comment by nangge** [comment]
我也无法确定你的问题，但在linux环境下的确会通信失败；现在因为网络原因我也无法push、pull代码，但如果你是最新代码，并且windows环境下，应该不会出现该问题。ps：我的测试环境wamp2.5（php 5.5.12）

**Comment by Liberxue** [comment]
求大神帮忙指点下我也安装你说的用了wamp2.5（php 5.5.12）也是无法显示微信用户，请问您PHP环境都需要设置什么方便说下吗

**Comment by nangge** [comment]
你把src文件夹下的cookie文件删掉，应该就可以了

**Comment by Liberxue** [comment]
删除了也不行，提示 与微信服务器通讯出错，请刷新重试或重新扫码登陆！   您那边方便帮忙远程处理下吗 大神，

**Comment by nangge** [comment]
+Q553212320

**Comment by Liberxue** [comment]
好的已加您了，请同意

**Comment by phphubert** [comment]
别人发送过来的图片 表情没法显示 不知道怎么做了...
